# Generated by Django 5.1.3 on 2024-12-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_customuser_role_departmenthead_secretary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='exam_date',
        ),
        migrations.AddField(
            model_name='exam',
            name='proffesor',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='exam',
            name='room',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
