# Generated by Django 5.1.3 on 2024-12-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_rename_location_room_building_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('long_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'tbl_faculty',
            },
        ),
    ]
