# Generated by Django 5.1.3 on 2024-12-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_remove_department_faculty_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingstaff',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
