# Generated by Django 5.1.3 on 2024-12-23 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialization',
            name='name',
        ),
    ]
