# Generated by Django 5.1.3 on 2024-12-23 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_remove_specialization_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
    ]
