# Generated by Django 5.1.3 on 2024-12-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_remove_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('ApprovedByProfessor', 'ApprovedByProfessor'), ('ApprovedBySecretary', 'ApprovedBySecretary'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
